name: CI

on:
  push:
  workflow_dispatch:

env:
  TERM: dumb

jobs:
  integration-test-for-cosmos:
    name: Cosmos DB integration test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup and execute Gradle task
        uses: gradle/gradle-build-action@v3
        with:
          arguments: run
